import assert from 'node:assert/strict';
import fs from 'node:fs';
const s = fs.readFileSync(new URL('../backend-server.mjs', import.meta.url), 'utf8');
assert.match(s, /OPENROUTER_MODEL.*qwen\\/qwen3\\.8-27b/);
assert.match(s, /OPENROUTER_FALLBACK_MODELS/);
assert.match(s, /if \(!hasImageParts\)/);
assert.match(s, /response_format: \{ type: 'json_object' \}/);
assert.match(s, /pathway_link\.requires_clinician_confirmation/);
assert.match(s, /provider: 'OpenRouter'/);
console.log('provider regression: PASS — OpenRouter/Qwen free-vision pathway');
