import assert from 'node:assert/strict';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const suite = fs.readFileSync(new URL('./frontend/v14.1-opd-suite.js', import.meta.url), 'utf8');
const nav = fs.readFileSync(new URL('./frontend/v14.2-clinical-navigation.js', import.meta.url), 'utf8');
const prostate = fs.readFileSync(new URL('./frontend/v14.3-prostate-pathway.js', import.meta.url), 'utf8');
const oncology = fs.readFileSync(new URL('./frontend/v14.4-oncology-pathways.js', import.meta.url), 'utf8');
const urgent = fs.readFileSync(new URL('./frontend/v14.5-urgent-urology.js', import.meta.url), 'utf8');
const stone = fs.readFileSync(new URL('./frontend/v14.6-stone-engine.js', import.meta.url), 'utf8');
const stricture = fs.readFileSync(new URL('./frontend/v14.7-stricture-engine.js', import.meta.url), 'utf8');
const bph = fs.readFileSync(new URL('./frontend/v14.8-bph-engine.js', import.meta.url), 'utf8');
const scores = fs.readFileSync(new URL('./frontend/v14.9-scores-engine.js', import.meta.url), 'utf8');
const atlas = fs.readFileSync(new URL('./frontend/v15.0-operative-atlas.js', import.meta.url), 'utf8');
const atlas2 = fs.readFileSync(new URL('./frontend/v15.1-operative-atlas-bph-recon.js', import.meta.url), 'utf8');
const atlas3 = fs.readFileSync(new URL('./frontend/v15.2-operative-atlas-oncology-recon.js', import.meta.url), 'utf8');
const atlas4 = fs.readFileSync(new URL('./frontend/v15.3-operative-atlas-rplnd-ureter-ecirs.js', import.meta.url), 'utf8');
const atlas5 = fs.readFileSync(new URL('./frontend/v15.4-operative-atlas-advanced-stone.js', import.meta.url), 'utf8');
const hotfix = fs.readFileSync(new URL('./frontend/v14-release-hotfix.js', import.meta.url), 'utf8');

execFileSync(process.execPath, ['--check', new URL('./frontend/v14.1-opd-suite.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14-release-hotfix.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.2-clinical-navigation.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.3-prostate-pathway.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.4-oncology-pathways.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.5-urgent-urology.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.6-stone-engine.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.7-stricture-engine.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.8-bph-engine.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v14.9-scores-engine.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v15.0-operative-atlas.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v15.1-operative-atlas-bph-recon.js', import.meta.url).pathname], {stdio:'pipe'});
execFileSync(process.execPath, ['--check', new URL('./frontend/v15.2-operative-atlas-oncology-recon.js', import.meta.url).pathname], {stdio:'pipe'});

assert.ok(nav.includes('Clinical Oracle'));
assert.ok(nav.includes('Bladder cancer pathway'));
assert.ok(nav.includes('Second TURBT indicated'));
assert.ok(nav.includes('enfortumab vedotin + pembrolizumab'));
assert.ok(nav.includes('cisplatin/gemcitabine + durvalumab'));
assert.ok(nav.includes('v142ClinicalNav'));
assert.ok(prostate.includes('Prostate cancer pathway'));
assert.ok(prostate.includes('ISUP Grade Group'));
assert.ok(prostate.includes('PEACE-1'));
assert.ok(prostate.includes('ARASENS'));
assert.ok(prostate.includes('STAMPEDE'));
assert.ok(oncology.includes('Kidney cancer pathway'));
assert.ok(oncology.includes('Upper tract urothelial cancer pathway'));
assert.ok(oncology.includes('Testicular cancer pathway'));
assert.ok(urgent.includes('Urgent urology'));
assert.ok(urgent.includes('Obstructed infected system'));
assert.ok(urgent.includes('Testicular torsion'));
assert.ok(urgent.includes('Fournier'));
assert.ok(urgent.includes('Ischaemic priapism'));
assert.ok(urgent.includes('clot retention'));
assert.ok(stone.includes('Stone disease decision engine'));
assert.ok(stone.includes('infected obstructed system'));
assert.ok(stone.includes('PCNL'));
assert.ok(stone.includes('RIRS'));
assert.ok(stone.includes('staghorn'));
assert.ok(stone.includes('simultaneous multi-access workflow'));
assert.ok(stricture.includes('Urethral stricture reconstruction pathway'));
assert.ok(stricture.includes('transecting EPA'));
assert.ok(stricture.includes('free-graft urethroplasty'));
assert.ok(bph.includes('BPH / male LUTS treatment engine'));
assert.ok(bph.includes('TUIP'));
assert.ok(bph.includes('30–80 mL'));
assert.ok(bph.includes('pressure-flow urodynamics'));
assert.ok(scores.includes('Urology scores & calculators'));
assert.ok(scores.includes('STONE'));
assert.ok(scores.includes('ISUP Grade Group'));
assert.ok(scores.includes('Clavien–Dindo'));
assert.ok(scores.includes('race-free modified'));
assert.ok(atlas.includes('RIRS / Flexible Ureteroscopy'));
assert.ok(atlas.includes('PCNL'));
assert.ok(atlas.includes('Operative sequence'));
assert.ok(atlas.includes('Bailout / staging'));
assert.ok(atlas2.includes('TURP'));
assert.ok(atlas2.includes('HOLEP'));
assert.ok(atlas2.includes('URETHROPLASTY'));
assert.ok(atlas2.includes('Safety checkpoints'));
assert.ok(atlas3.includes('Radical Prostatectomy'));
assert.ok(atlas3.includes('Radical Cystectomy'));
assert.ok(atlas3.includes('Partial Nephrectomy'));
assert.ok(atlas3.includes('Anderson–Hynes Dismembered Pyeloplasty'));
assert.ok(atlas4.includes('Retroperitoneal Lymph Node Dissection'));
assert.ok(atlas4.includes('Ureteric Reconstruction'));
assert.ok(atlas4.includes('ECIRS / Combined PCNL + RIRS'));
assert.ok(atlas5.includes('Mini-PCNL'));
assert.ok(atlas5.includes('Supine PCNL'));
assert.ok(atlas5.includes('Tubeless / Totally Tubeless PCNL'));
assert.ok(atlas5.includes('Antegrade Ureteroscopy'));
assert.ok(atlas5.includes('Laparoscopic / Open Ureterolithotomy'));
assert.ok(atlas5.includes('Pyelolithotomy'));
assert.ok(oncology.includes('BEP'));
assert.ok(suite.includes('OPD quick tools'));
assert.ok(!hotfix.includes("document.title='Urology Oracle V14.0"));
assert.ok(!hotfix.includes("h.textContent='Urology Oracle V14.0"));
console.log('UI regression: PASS');
